project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Ajinkya Ranade
      - biography.qmd
      - research.qmd
      - publications.qmd
      - presentations.qmd
      - awards.qmd
      - miscellaneous.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ajinkya-ranade-phd-b4b899130/
        target: _blank
      - icon: 1-circle
        href: https://orcid.org/my-orcid?orcid=0000-0003-3945-2656
        target: _blank
      - icon: 2-circle
        href: https://www.researchgate.net/profile/Ajinkya-Ranade
        target: _blank
      - icon: 3-circle
        href: https://scholar.google.com/citations?user=Yir-Mq8AAAAJ&hl=en
        target: _blank
      - icon: envelope
        href: mailto:ajinkyaranade3@gmail.com

format:
  html:
    theme: Cerulean #Materia
    # highlight-style: pygments
    # linkcolor: "#001FFD"
    css: styles.css
    toc: true
    page-layout: full

editor: visual
