---
title: "About"
---

::: {style="text-align: justify"}
An analytical chemist with interdisciplinary research experience in graphene technology, optoelectronics, and wastewater treatment exploring opportunities to innovate sustainable treatment technologies in the research and development sector. I aim to utilize my interdisciplinary background for innovation in clean energy and tackling the water-energy nexus to achieve a sustainable future. Currently looking for organizations that will provide me ample scope to nurture this interest and develop my skills.

-   Expertise in individual (adsorption, photocatalysis, biodegradation ) and synergic (intimately coupled photocatalytic biodegradation) wastewater treatment technologies with a critical focus on sustainability
-   Expertise in materials engineering, graphene technology, semiconductor technology and optoelectronics
-   Expertise in fabrication of high-quality monolayer graphene using (atmospheric and low pressure) chemical vapor deposition techniques
-   Published three first author publication and 9 co-author publications
-   Recent publication in the prestigious Water Research Journal
:::
